Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import chr0oejke
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import chr0oejke
ModuleNotFoundError: No module named 'chr0oejke'
>>> import chrome
>>> import wifi
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import wifi
ModuleNotFoundError: No module named 'wifi'
>>> import wi-fi
SyntaxError: invalid syntax
>>> 
==== RESTART: C:\Users\ELCOT\AppData\Local\Programs\Python\Python38\wi-fi.py ===
Redmi Note 9 Pro              |jayavelangj
Traceback (most recent call last):
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python38\wi-fi.py", line 9, in <module>
    print("{:<30}|{:<}".format(i,results[0]))
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python38\wi-fi.py", line 10, in <module>
    except indexError:
NameError: name 'indexError' is not defined
>>> 
==== RESTART: C:\Users\ELCOT\AppData\Local\Programs\Python\Python38\wi-fi.py ===
Redmi Note 9 Pro              |jayavelangj
Traceback (most recent call last):
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python38\wi-fi.py", line 9, in <module>
    print("{:<30}|{:<}".format(i,results[0]))
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python38\wi-fi.py", line 10, in <module>
    except indexError:
NameError: name 'indexError' is not defined
>>> 	i
	
SyntaxError: unexpected indent
>>> 
>>> 
>>> 
>>> l=list("10 20 20 10 10 30 50 10 20")
>>> l
['1', '0', ' ', '2', '0', ' ', '2', '0', ' ', '1', '0', ' ', '1', '0', ' ', '3', '0', ' ', '5', '0', ' ', '1', '0', ' ', '2', '0']
>>> l="10 20 20 10 10 30 50 10 20".split()
>>> l
['10', '20', '20', '10', '10', '30', '50', '10', '20']
>>> l.find('10')
Traceback (most recent call last):
  File "<pyshell#12>", line 1, in <module>
    l.find('10')
AttributeError: 'list' object has no attribute 'find'
>>> find(l)
Traceback (most recent call last):
  File "<pyshell#13>", line 1, in <module>
    find(l)
NameError: name 'find' is not defined
>>> 
>>> 
>>> 
>>> 
>>> l
['10', '20', '20', '10', '10', '30', '50', '10', '20']
>>> "10 20 20 10 10 30 50 10 20".count('10')
4
>>> a=[]
>>> l="10 20 20 10 10 30 50 10 20"
>>> for i in range(len(l)):
	a.append(l.count(l[i]))

	
>>> a
[4, 9, 8, 3, 9, 8, 3, 9, 8, 4, 9, 8, 4, 9, 8, 1, 9, 8, 1, 9, 8, 4, 9, 8, 3, 9]
>>> len(l,a)
Traceback (most recent call last):
  File "<pyshell#29>", line 1, in <module>
    len(l,a)
TypeError: len() takes exactly one argument (2 given)
>>> len(al)
Traceback (most recent call last):
  File "<pyshell#30>", line 1, in <module>
    len(al)
NameError: name 'al' is not defined
>>> len(a)
26
>>> len(l)
26
>>> for i in range(len(l)):
	a.append(l.count(i))

	
Traceback (most recent call last):
  File "<pyshell#34>", line 2, in <module>
    a.append(l.count(i))
TypeError: must be str, not int
>>> for i in range(len(l)):
	a.append(l.count(i))

	
Traceback (most recent call last):
  File "<pyshell#36>", line 2, in <module>
    a.append(l.count(i))
TypeError: must be str, not int

>>> l
'10 20 20 10 10 30 50 10 20'
>>> ll
Traceback (most recent call last):
  File "<pyshell#38>", line 1, in <module>
    ll
NameError: name 'll' is not defined
a
>>> 
>>> a
[4, 9, 8, 3, 9, 8, 3, 9, 8, 4, 9, 8, 4, 9, 8, 1, 9, 8, 1, 9, 8, 4, 9, 8, 3, 9]
>>> ll=[]
>>> a=[]
>>> for i in range(len(l)):
	a.append(l.count(ll[i]))

	
Traceback (most recent call last):
  File "<pyshell#44>", line 2, in <module>
    a.append(l.count(ll[i]))
IndexError: list index out of range
>>> for i in range(len(ll)):
	a.append(l.count(ll[i]))

	
>>> a
[]
>>> l
'10 20 20 10 10 30 50 10 20'
>>> ll
[]
>>> a
[]
>>> ll=['10' ,'20' ,'20' ,'10' ,'10', '30' ,'50' ,'10' ,'20']
>>> ll
['10', '20', '20', '10', '10', '30', '50', '10', '20']
>>> for i in range(len(ll)):
	a.append(l.count(ll[i]))

	
>>> a
[4, 3, 3, 4, 4, 1, 1, 4, 3]
>>> 
= RESTART: C:/Users/ELCOT/AppData/Local/Programs/Python/Python38/sales_by_mathes.py
9
'10 20 20 10 10 30 50 10 20'
>>> a
[]
>>> 
= RESTART: C:/Users/ELCOT/AppData/Local/Programs/Python/Python38/sales_by_mathes.py
9
10 20 20 10 10 30 50 10 20
>>> a
[]
>>> 
= RESTART: C:/Users/ELCOT/AppData/Local/Programs/Python/Python38/sales_by_mathes.py
9
10 20 20 10 10 30 50 10 20
>>> a
[]
>>> 
= RESTART: C:/Users/ELCOT/AppData/Local/Programs/Python/Python38/sales_by_mathes.py
9
10 20 20 10 10 30 50 10 20
>>> a
[]
>>> 
= RESTART: C:/Users/ELCOT/AppData/Local/Programs/Python/Python38/sales_by_mathes.py
9
10 20 20 10 10 30 50 10 20
>>> a
[]
>>> s
'10 20 20 10 10 30 50 10 20'
>>> l
['10', '20', '20', '10', '10', '30', '50', '10', '20']
>>> ll
[]
>>> 
= RESTART: C:/Users/ELCOT/AppData/Local/Programs/Python/Python38/sales_by_mathes.py
9
10 20 20 10 10 30 50 10 20
>>> a
[4, 3, 3, 4, 4, 1, 1, 4, 3]
>>> set(a)
{1, 3, 4}
>>> aa=set(a)
>>> aa
{1, 3, 4}
>>> for i in aa:
	print(i)

	
1
3
4
>>> r=0
>>> for i in aa:
	if(i%2==0):

		
KeyboardInterrupt
>>> r=[]
>>> for i in aa:
	if(i%2==0):
		r.append(i)

		
>>> r
[4]
>>> for i in aa:
	if(i//2==1):
		r.append(i)

		
>>> r
[4, 3]
>>> for i in aa:
	if(i//2==1):
		r.append(i)

		
>>> r
[4, 3, 3]
>>> for i in aa:
	if(i//2==1 and i%2==0):
		r.append(i)

		
>>> r
[4, 3, 3]
>>> r=[]
>>> for i in aa:
	if(i//2==1 and i%2==0):
		r.append(i)

		
>>> r
[]
>>> 3%2
1
>>> 3%6
3
>>> 3%5
3
>>> 2//5
0
>>> 17/2
8.5
>>> ceil(8.5)
Traceback (most recent call last):
  File "<pyshell#100>", line 1, in <module>
    ceil(8.5)
NameError: name 'ceil' is not defined
>>> import math
>>> math.ceil(8.5)
9
>>> aa
{1, 3, 4}
>>> r
[]
>>> for i in aa:
	r.append(math.ceil(i/2))

	
>>> r
[1, 2, 2]
>>> aa=set(8,3,7)
Traceback (most recent call last):
  File "<pyshell#110>", line 1, in <module>
    aa=set(8,3,7)
TypeError: set expected at most 1 argument, got 3
>>> aa=set({8,3,7})
>>> aa
{8, 3, 7}
>>> type(aa)
<class 'set'>
>>> for i in aa:
	r.append(math.ceil(i/2))

	
>>> r
[1, 2, 2, 4, 2, 4]
>>> r.clear()
>>> r
[]
>>> for i in aa:
	r.append(math.ceil(i/2))

	
>>> r
[4, 2, 4]
>>> r.clear()
>>> for i in aa:
	r.append(math.floor(i/2))

	
>>> r
[4, 1, 3]
>>> r.clear()
>>> r
[]
>>> aa={1,2,44,55,8,9,6,3}
>>> for i in aa:
	r.append(math.floor(i/2))

	
>>> aa
{1, 2, 3, 6, 8, 9, 44, 55}
>>> r
[0, 1, 1, 3, 4, 4, 22, 27]
>>> 55/2
27.5
>>> 
= RESTART: C:/Users/ELCOT/AppData/Local/Programs/Python/Python38/sales_by_mathes.py
9                           
10 20 20 10 10 30 50 10 20
Traceback (most recent call last):
  File "C:/Users/ELCOT/AppData/Local/Programs/Python/Python38/sales_by_mathes.py", line 10, in <module>
    r.append(math.floor(i/2))
NameError: name 'math' is not defined
>>> 
= RESTART: C:/Users/ELCOT/AppData/Local/Programs/Python/Python38/sales_by_mathes.py
9
10 20 20 10 10 30 50 10 20
3
>>> 
= RESTART: C:/Users/ELCOT/AppData/Local/Programs/Python/Python38/sales_by_mathes.py

Traceback (most recent call last):
  File "C:/Users/ELCOT/AppData/Local/Programs/Python/Python38/sales_by_mathes.py", line 2, in <module>
    n=int(input())
ValueError: invalid literal for int() with base 10: ''
>>> 
= RESTART: C:/Users/ELCOT/AppData/Local/Programs/Python/Python38/sales_by_mathes.py
15
6 5 2 3 5 2 2 1 1 5 1 3 3 3 5
3
>>> r
[0, 1, 2]
>>> rr
Traceback (most recent call last):
  File "<pyshell#135>", line 1, in <module>
    rr
NameError: name 'rr' is not defined
>>> aa
{1, 3, 4}
>>> 
= RESTART: C:/Users/ELCOT/AppData/Local/Programs/Python/Python38/sales_by_mathes.py
15
6 5 2 3 5 2 2 1 1 5 1 3 3 3 5
3
>>> a
[1, 4, 3, 4, 4, 3, 3, 3, 3, 4, 3, 4, 4, 4, 4]
>>> len(a)
15
>>> aa
{1, 3, 4}
>>> 